package edu.westga.cs3230.healthcare_dbms.sql;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Indicates that this field is automatically generated by the ID, such as an auto increment key.
 *
 * @author Joseph Fuller
 */
@Retention(RetentionPolicy.RUNTIME)
public @interface SqlGenerated {

}
